from django.urls import path
from . import views

app_name = "admin_panel"

urlpatterns = [
    path("", views.admin_dashboard_view, name="admin_dashboard"),
    path("admin_dashboard/", views.admin_dashboard_view, name="admin_dashboard_redundant"),
    path("movies/", views.movies_list_view, name="movies_list"),
    path("add-movie/", views.add_movie, name="add_movie"),
    path("edit-movie/<int:movie_id>/", views.edit_movie, name="edit_movie"),
    path("delete-movie/<int:movie_id>/", views.delete_movie, name="delete_movie"),
    path("genres/", views.genres_list_view, name="genres_list"),
    path("add-genre/", views.add_genre, name="add_genre"),
    path("edit-genre/<int:genre_id>/", views.edit_genre, name="edit_genre"),
    path("delete-genre/<int:genre_id>/", views.delete_genre, name="delete_genre"),
    path("cast_and_crew/", views.cast_crew_list_view, name="cast_crew_list"),
    path("add-person/", views.add_person, name="add_person"),
    path("edit-person/<int:person_id>/", views.edit_person, name="edit_person"),
    path("delete-person/<int:person_id>/", views.delete_person, name="delete_person"),
    path("assign-cast/", views.assign_cast, name="assign_cast"),
    path("delete-cast/<int:cast_id>/", views.delete_cast, name="delete_cast"),
    path("users/", views.users_list_view, name="users_list"),
    path("user-detail/<int:u_id>/", views.user_detail_view, name="user_detail"),
    path("toggle-user-status/<int:u_id>/", views.toggle_user_status, name="toggle_user_status"),
    path("toggle-admin-status/<int:u_id>/", views.toggle_admin_status, name="toggle_admin_status"),
    path("assign-privileges/<int:u_id>/", views.assign_admin_privileges, name="assign_admin_privileges"),
    path("delete-user/<int:u_id>/", views.delete_user, name="delete_user"),
    path("ratings/", views.ratings_list_view, name="ratings_list"),
    path("delete-rating/<int:rating_id>/", views.delete_rating, name="delete_rating"),
    path("delete-log/<int:log_id>/", views.delete_activity_log, name="delete_activity_log"),
    path("database/", views.database_stats_view, name="database_stats"),
    path("train-ml/", views.train_ml_dedicated_view, name="train_ml"),
    path("train-ml-ajax/", views.train_ml_ajax_view, name="train_ml_ajax"),
    path("messages/", views.contact_messages_list_view, name="contact_messages_list"),
    path("update-message-status/<int:message_id>/<str:new_status>/", views.update_contact_message_status, name="update_message_status"),
    path("clear-all-messages/", views.clear_all_contact_messages, name="clear_all_messages"),
    path("delete-message/<int:message_id>/", views.delete_contact_message, name="delete_contact_message"),
    path("login/", views.admin_login_view, name="admin_login"),
    path("verify-2fa/", views.admin_verify_2fa_view, name="admin_verify_2fa"),
    path("resend-2fa/", views.admin_resend_2fa_view, name="admin_resend_2fa"),
    path("logout/", views.admin_logout_view, name="admin_logout"),
    path("change-password/", views.change_password_view, name="change_password"),
    path("simulate-feedback-ajax/", views.simulate_feedback_ajax, name="simulate_feedback_ajax"),
]
