# Generated by Django 6.0.1 on 2026-04-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0021_mlmodels_version_alter_mlmodels_trained_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterColorProfile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('dominant_hex', models.CharField(blank=True, max_length=10, null=True)),
                ('palette_json', models.TextField(blank=True, null=True)),
                ('brightness', models.FloatField(default=0.0)),
                ('saturation', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color_profile', to='ml_models.movies')),
            ],
            options={
                'db_table': 'ml_models_postercolorprofile',
            },
        ),
    ]
